FROM node:18-alpine

WORKDIR /app

# Copia dependencias y las instala
COPY package*.json ./
RUN npm install

# Copia todo el código del frontend
COPY . .

# Construye para producción
RUN npx nuxi build

# Expone el puerto de preview
EXPOSE 3000

# Corre el servidor de Nuxt en modo preview
CMD ["npx", "nuxi", "preview", "--host", "0.0.0.0", "--port", "3000"]
