version: '3.9'

services:
  mysql:
    image: mariadb:10.6
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: barberia
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      interval: 10s
      retries: 10

  backend:
    build:
      context: ./backend
    container_name: fastapi
    restart: unless-stopped
    expose:
      - "8000"
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./backend:/app
    working_dir: /app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --proxy-headers --forwarded-allow-ips="*"
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
      MYSQL_DATABASE: barberia
      CORS_ORIGINS: https://zyma.lat,https://www.zyma.lat,https://api.zyma.lat
      LOG_LEVEL: info

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: nuxt
    restart: unless-stopped
    expose:
      - "3000"
    depends_on:
      - backend
    environment:
      NUXT_PORT: 3000
      NUXT_HOST: 0.0.0.0
      NUXT_PUBLIC_API_BASE_URL: /api

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/prod.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/www:/var/www/certbot
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - frontend
      - backend

volumes:
  mysql_data:
