version: '3.9'

services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: ./backend
    container_name: fastapi
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    volumes:
      - ./backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - .env.development  # Se cargan las variables desde el archivo .env

  frontend:
    build:
      context: ./frontend
    container_name: nuxt
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app:delegated
      - /app/node_modules
    command: npx nuxi dev --host 0.0.0.0 --port 3000
    environment:
      - NUXT_PORT=3000
      - NUXT_HOST=0.0.0.0
      - CHOKIDAR_USEPOLLING=true

volumes:
  mysql_data:
