version: '3.9'

services:
  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: barberia
      MYSQL_USER: barberuser
      MYSQL_PASSWORD: barberpass
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: fastapi
    restart: always
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: nuxt
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
