"""mensaje

Revision ID: 134b7e0347db
Revises: 9e9c9b566f86
Create Date: 2025-05-15 23:12:00.756372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '134b7e0347db'
down_revision: Union[str, None] = '9e9c9b566f86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('documento', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'documento')
    # ### end Alembic commands ###
