"""crear tablas iniciales

Revision ID: 13c77f0fefc2
Revises: df23e87eb831
Create Date: 2025-05-16 01:02:12.391340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '13c77f0fefc2'
down_revision: Union[str, None] = 'df23e87eb831'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permisos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('clave', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clave'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('tipos_perfil',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('clave', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('campos_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clave')
    )
    op.create_table('perfiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('persona_id', sa.Integer(), nullable=False),
    sa.Column('tipo_perfil_id', sa.Integer(), nullable=False),
    sa.Column('datos_personalizados_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ),
    sa.ForeignKeyConstraint(['tipo_perfil_id'], ['tipos_perfil.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('persona_id', 'tipo_perfil_id', name='ux_perfiles_persona_tipo')
    )
    op.create_table('configuraciones',
    sa.Column('clave', sa.String(length=100), nullable=False),
    sa.Column('valor', sa.Text(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('tipo', sa.Enum('string', 'int', 'bool', 'json', name='tipoconfigenum'), server_default='string', nullable=False),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['creado_por'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('clave')
    )
    op.create_table('logs_usuarios',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('accion', sa.String(length=255), nullable=False),
    sa.Column('tabla_afectada', sa.String(length=100), nullable=True),
    sa.Column('registro_id', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('detalles_json', sa.Text(), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('navegador', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles_permisos',
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.Column('permiso_id', sa.Integer(), nullable=False),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['creado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['permiso_id'], ['permisos.id'], ),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('rol_id', 'permiso_id')
    )
    op.create_table('tokens',
    sa.Column('token', sa.String(length=36), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('tipo_token', sa.Enum('access', 'refresh', 'api', name='tipotokenenum'), nullable=True),
    sa.Column('expiracion', sa.DateTime(), nullable=False),
    sa.Column('revocado', sa.Boolean(), nullable=False),
    sa.Column('revocado_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('token')
    )
    op.drop_index('ix_barbers_id', table_name='barbers')
    op.drop_table('barbers')
    op.alter_column('personas', 'genero',
               existing_type=mysql.CHAR(length=1),
               comment='M: Masculino, F: Femenino, O: Otro',
               existing_nullable=False)
    op.alter_column('personas', 'direccion_cifrada',
               existing_type=sa.VARBINARY(length=512),
               type_=sa.LargeBinary(length=512),
               existing_nullable=True)
    op.alter_column('personas', 'telefono_cifrado',
               existing_type=sa.VARBINARY(length=128),
               type_=sa.LargeBinary(length=128),
               existing_nullable=True)
    op.alter_column('personas', 'correo_cifrado',
               existing_type=sa.VARBINARY(length=256),
               type_=sa.LargeBinary(length=256),
               existing_nullable=True)
    op.alter_column('personas', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('personas', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.drop_index('ix_personas_id', table_name='personas')
    op.create_index('idx_apellidos', 'personas', ['apellido_paterno', 'apellido_materno'], unique=False)
    op.add_column('roles', sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.add_column('roles', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.alter_column('roles', 'descripcion',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index('ix_roles_id', table_name='roles')
    op.drop_column('roles', 'documento')
    op.drop_column('roles', 'foto')
    op.alter_column('usuarios', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('usuarios', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.drop_index('ix_usuarios_id', table_name='usuarios')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_usuarios_id', 'usuarios', ['id'], unique=False)
    op.alter_column('usuarios', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('usuarios', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.add_column('roles', sa.Column('foto', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('roles', sa.Column('documento', mysql.VARCHAR(length=255), nullable=True))
    op.create_index('ix_roles_id', 'roles', ['id'], unique=False)
    op.alter_column('roles', 'descripcion',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.drop_column('roles', 'updated_at')
    op.drop_column('roles', 'created_at')
    op.drop_index('idx_apellidos', table_name='personas')
    op.create_index('ix_personas_id', 'personas', ['id'], unique=False)
    op.alter_column('personas', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('personas', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('personas', 'correo_cifrado',
               existing_type=sa.LargeBinary(length=256),
               type_=sa.VARBINARY(length=256),
               existing_nullable=True)
    op.alter_column('personas', 'telefono_cifrado',
               existing_type=sa.LargeBinary(length=128),
               type_=sa.VARBINARY(length=128),
               existing_nullable=True)
    op.alter_column('personas', 'direccion_cifrada',
               existing_type=sa.LargeBinary(length=512),
               type_=sa.VARBINARY(length=512),
               existing_nullable=True)
    op.alter_column('personas', 'genero',
               existing_type=mysql.CHAR(length=1),
               comment=None,
               existing_comment='M: Masculino, F: Femenino, O: Otro',
               existing_nullable=False)
    op.create_table('barbers',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('servicios', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('edad', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_barbers_id', 'barbers', ['id'], unique=False)
    op.drop_table('tokens')
    op.drop_table('roles_permisos')
    op.drop_table('logs_usuarios')
    op.drop_table('configuraciones')
    op.drop_table('perfiles')
    op.drop_table('tipos_perfil')
    op.drop_table('permisos')
    # ### end Alembic commands ###
