"""crear tablas iniciales

Revision ID: 849f67aaaca5
Revises: 3415fbf90810
Create Date: 2025-05-15 22:47:05.457331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '849f67aaaca5'
down_revision: Union[str, None] = '3415fbf90810'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('barbers', sa.Column('servicios', sa.String(length=255), nullable=True))
    op.drop_column('barbers', 'service')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('barbers', sa.Column('service', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('barbers', 'servicios')
    # ### end Alembic commands ###
