"""crear tablas iniciales

Revision ID: cea3270f525b
Revises: 849f67aaaca5
Create Date: 2025-05-15 22:50:13.375379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cea3270f525b'
down_revision: Union[str, None] = '849f67aaaca5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('barbers', sa.Column('edad', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('barbers', 'edad')
    # ### end Alembic commands ###
